---
# tasks file for nginx_proxy

- name: Установка Nginx
  apt:
    name: "nginx"
    state: present
  when: "'vm_2' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_2
- name: Настройка прокси
  ansible.builtin.template:
    src: index_for_proxy.j2
    dest: /etc/nginx/nginx.conf
  when: "'vm_2' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_2
  notify: "Nginx Reloader"
